CREATE DATABASE IF NOT EXISTS taskmate CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE taskmate;

CREATE TABLE IF NOT EXISTS tasks (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(500) NULL,
  priority ENUM('Alta', 'Media', 'Baja') NOT NULL DEFAULT 'Media',
  completed TINYINT(1) NOT NULL DEFAULT 0,
  category VARCHAR(100) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
